development:
  adapter: postgresql
  encoding: utf8
  database: myflix_development
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: utf8
  database: myflix_test
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
